#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : The StaticFrame Book  # The title of the book. Will be placed in the left navbar.
author                      : Investment Systems  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : sf-logo-web_icon.png
